<?php $customer = $block->getCustomer(); ?>
<div class="container main-container vendor-container">
    <h1><?= __('Suggest a source'); ?></h1>
    <div class="row">
        <div class="col-md-12 container form-container">
            <form name="suggest_source"
                  id="suggest_source"
                  action="<?php echo $block->getUrl('*/*/savesource') ?>"
                  method="post">

                <h3><?= __('General'); ?></h3>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <div class="col-md-12 label-container">
                                <label for="name">
                                    <?= __('Name'); ?>
                                    <span class="required">*</span>:
                                </label>
                            </div>
                            <div class="col-md-12 input-container">
                                <input type="text"
                                       id="name"
                                       name="name"
                                       class="input-text form-control required-entry"
                                />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12 label-container">
                                <label for="code">
                                    <?= __('Code'); ?>
                                    <span class="required">*</span>:
                                </label>
                            </div>
                            <div class="col-md-12 input-container">
                                <input type="text"
                                       id="code"
                                       name="code"
                                       class="input-text form-control required-entry no-whitespace"
                                />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12 label-container">
                                <label for="description">
                                    <?= __('Description'); ?>
                                </label>
                            </div>
                            <div class="col-md-12 input-container">
                                <textarea id="description"
                                          name="description"
                                          class="input-text form-control form-control wysiwyg"
                                          rows="15"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12 label-container">
                                <label for="latitude">
                                    <?= __('Latitude'); ?>
                                </label>
                            </div>
                            <div class="col-md-12 input-container">
                                <input type="text"
                                       id="latitude"
                                       name="latitude"
                                       class="input-text form-control"
                                />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12 label-container">
                                <label for="longitude">
                                    <?= __('Longitude'); ?>
                                </label>
                            </div>
                            <div class="col-md-12 input-container">
                                <input type="text"
                                       id="longitude"
                                       name="longitude"
                                       class="input-text form-control"
                                />
                            </div>
                        </div>
                    </div>
                </div>
                <hr/>
                <h3><?= __('Contact Info'); ?></h3>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <div class="col-md-12 label-container">
                                <label for="contact-name">
                                    <?= __('Contact Name'); ?>
                                </label>
                            </div>
                            <div class="col-md-12 input-container">
                                <input type="text"
                                       id="contact-name"
                                       name="contact-name"
                                       class="input-text form-control"
                                />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12 label-container">
                                <label for="email">
                                    <?= __('Email'); ?>
                                </label>
                            </div>
                            <div class="col-md-12 input-container">
                                <input type="text"
                                       id="email"
                                       name="email"
                                       class="input-text form-control validate-email"
                                />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12 label-container">
                                <label for="phone">
                                    <?= __('Phone'); ?>
                                </label>
                            </div>
                            <div class="col-md-12 input-container">
                                <input type="text"
                                       id="phone"
                                       name="phone"
                                       class="input-text form-control"
                                />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12 label-container">
                                <label for="fax">
                                    <?= __('Fax'); ?>
                                </label>
                            </div>
                            <div class="col-md-12 input-container">
                                <input type="text"
                                       id="fax"
                                       name="fax"
                                       class="input-text form-control validate-fax"
                                />
                            </div>
                        </div>
                    </div>
                </div>
                <hr/>
                <h3><?= __('Address Data'); ?></h3>
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <div class="col-md-12 label-container">
                                <label for="country">
                                    <?= __('Country'); ?>
                                    <span class="required">*</span>:
                                </label>
                            </div>
                            <div class="col-md-12 input-container">
                                <?= $block->getCountryHtmlSelect() ?>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12 label-container">
                                <label for="region_id">
                                    <?= __('Region'); ?>
                                </label>
                            </div>
                            <div class="col-md-12 input-container">
                                <select id="region_id" name="region_id"
                                        class="validate-select region_id" style="display:none;">
                                    <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                                </select>
                                <input type="text"
                                       id="region"
                                       name="region"
                                       class="input-text validate-not-number-first <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region')) ?>" />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12 label-container">
                                <label for="city">
                                    <?= __('City'); ?>
                                </label>
                            </div>
                            <div class="col-md-12 input-container">
                                <input type="text"
                                       id="city"
                                       name="city"
                                       class="input-text form-control"
                                />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12 label-container">
                                <label for="street">
                                    <?= __('Street'); ?>
                                </label>
                            </div>
                            <div class="col-md-12 input-container">
                                <input type="text"
                                       id="street"
                                       name="street"
                                       class="input-text form-control"
                                />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12 label-container">
                                <label for="postcode">
                                    <?= __('Postcode'); ?>
                                    <span class="required">*</span>:
                                </label>
                            </div>
                            <div class="col-md-12 input-container">
                                <input type="text"
                                       id="postcode"
                                       name="postcode"
                                       class="input-text form-control required validate-zip-international <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode')) ?>"
                                />
                                <div role="alert" class="message warning" style="display:none">
                                    <span></span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <hr/>
                <div class="col-md-2 row">
                    <input type="submit"
                           name="submit"
                           class="btn btn-primary"
                           value="<?php echo __('Submit Source') ?>"/>
                </div>
            </form>
        </div>
    </div>
</div>

<script type="text/x-magento-init">
    {

        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#postcode",
                "form": "#suggest_source",
                "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                "defaultRegion": "<?= (int) $block->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
            }
        },
        "#suggest_source": {
            "validation": {}
        }
    }
</script>
