<?php $_items = $block->getCollection(); ?>
<?php $isDiscountEff = $block->isDiscountEffective(); ?>
<?php $currencyHelper = $block->getCurrencyHelper(); ?>

<div class="container-fluid main-container vendor-container">
        <h1><?php echo $block->escapeHtml(__('Order Totals') )?></h1>
        <div class="jumbotron">
            <form name="report_filter" id="report_filter" action="" method="post" enctype="multipart/form-data">
                <div class="row">
                    <div class="col-md-2">
                        <select id="sales_report_period_type" name="period_type" title="Period" class="form-control select">
                            <option value="day"><?php  /* @escapeNotVerified */ echo __('Day')?></option>
                            <option value="month"><?php  /* @escapeNotVerified */ echo __('Month')?></option>
                            <option value="year"><?php  /* @escapeNotVerified */  echo __('Year')?></option>
                        </select>
                    </div>
                    <div class="col-md-3">
                        <input type="text" class="form-control datepicker input-text required-entry" name="from" value="<?php echo $block->getParam('from', ''); ?>" placeholder="<?php echo $block->escapeHtml(__('From'))?>*"/>
                    </div>
                    <div class="col-md-3">
                        <input type="text" class="form-control datepicker input-text required-entry" name="to" value="<?php echo $block->getParam('to', ''); ?>" placeholder="<?php echo $block->escapeHtml(__('To'))?>*"/>
                    </div>
                    <div class="col-md-2">
                        <input type="submit" name="submit" class="btn btn-primary btn-sm" value="<?php echo $block->escapeHtml(__('Show Report') )?>" />
                    </div>
                    <div class="col-md-2">
                        <input type="submit" name="submit" class="btn btn-info btn-sm" value="<?php echo $block->escapeHtml(__('Export to CSV') )?>" />
                    </div>
                </div>
            </form>
        </div>

    <div class="row">
        <div class='col-md-12'>
        <div class="table-responsive">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th class="text-center"><?php /* @escapeNotVerified */ echo __('Period'); ?></th>
                            <th class="text-center"><?php /* @escapeNotVerified */ echo __('Qty Sold'); ?></th>
                            <th class="text-center"><?php /* @escapeNotVerified */ echo __('Subtotal'); ?></th>
                            <th class="text-center"><?php /* @escapeNotVerified */ echo __('Net Income'); ?></th>
                            <?php if($isDiscountEff):?>
                                <th><?php echo /* @escapeNotVerified */  __('Discount')?></th>
                                <th><?php echo /* @escapeNotVerified */  __('With Discount')?></th>
                            <?php endif; ?>
                        </tr>
                        </thead>
                        <tbody>
                            <?php $sumQtySold = 0; ?>
                            <?php $sumSubtotal = 0; ?>
                            <?php $sumIncome = 0; ?>
                            <?php $sumDiscount = 0; ?>
                            <?php $sumIncomeWithDiscount = 0; ?>
                            <?php foreach($_items AS $_item) : ?>
                                <?php $sumQtySold += $_item->getSoldCount(); ?>
                                <?php $sumSubtotal += $_item->getSumPrice(); ?>
                                <?php $sumIncome += $_item->getVendorIncome(); ?>
                                <?php $sumDiscount += $_item->getData('sum_discount'); ?>
                                <?php $sumIncomeWithDiscount += $_item->getData('vendor_income_with_discount'); ?>
                                <tr>
                                    <td><?php echo $block->getPeriodString($_item->getCreatedAt()); ?></td>
                                    <td><?php echo number_format($_item->getSoldCount()); ?></td>
                                    <td><?php echo $currencyHelper->currency($_item->getSumPrice()); ?></td>
                                    <td><?php echo $currencyHelper->currency($_item->getVendorIncome()) ?></td>
                                    <?php if($isDiscountEff):?>
                                        <td><?php echo $currencyHelper->currency($_item->getData('sum_discount')) ?></td>
                                        <td><?php echo $currencyHelper->currency($_item->getData('vendor_income_with_discount')); ?></td>
                                    <?php endif; ?>
                                </tr>
                            <?php endforeach; ?>
                        </tbody>
                        <tfoot>
                        <tr>
                            <td class="info"><?php echo /* @escapeNotVerified */ __('Total'); ?></td>
                            <td class="info"><?php echo $block->escapeHtml($sumQtySold); ?></td>
                            <td class="info"><?php echo $currencyHelper->currency($sumSubtotal); ?></td>
                            <td class="info"><?php echo $currencyHelper->currency($sumIncome); ?></td>
                            <?php if($isDiscountEff):?>
                                <td class="info"><?php echo $currencyHelper->currency($sumDiscount); ?></td>
                                <td class="info"><?php echo $currencyHelper->currency($sumIncomeWithDiscount); ?></td>
                            <?php endif; ?>
                        </tr>
                        </tfoot>
                    </table>
                </div>
        </div>
    </div>
</div>
<script type="text/javascript">
  

    jQuery(document).ready(function($){
        $('.datepicker').datepicker();
    });
    //< ![CDATA[
    var customForm = new VarienForm('report_filter');
    //]]>
</script>