<?php $_items = $block->getCollection(); ?>
<div class="container-fluid main-container vendor-container">
        <h1><?php echo $block->escapeHtml($block->getTitle()) ?></h1>
        <div class="jumbotron">
            <form name="report_filter" id="report_filter" action="<?php echo $block->getUrl('*/*/*') ?>" method="post" enctype="multipart/form-data">
                <div class="row">
                    <div class="col-md-2">
                        <select id="sales_report_period_type" name="period_type" title="Period" class="select">
                            <option value="day"><?php echo $block->escapeHtml(__('Day'))?></option>
                            <option value="month"><?php echo $block->escapeHtml(__('Month'))?></option>
                            <option value="year"><?php echo $block->escapeHtml(__('Year'))?></option>
                        </select>
                    </div>
                    <div class="col-md-3">
                        <input type="text" class="form-control datepicker input-text required-entry" name="from" value="<?php echo $block->getParam('from', ''); ?>" placeholder="<?php echo $block->escapeHtml(__('From'))?>*"/>
                    </div>
                    <div class="col-md-3">
                        <input type="text" class="form-control datepicker input-text required-entry" name="to" value="<?php echo $block->getParam('to', ''); ?>" placeholder="<?php echo $block->escapeHtml(__('To'))?>*"/>
                    </div>
                    <div class="col-md-2">
                        <input type="submit" name="submit" class="btn btn-primary btn-sm" value="<?php echo $block->escapeHtml(__('Show Report') )?>" />
                    </div>
                    <div class="col-md-2">
                        <input type="submit" name="submit" class="btn btn-info btn-sm" value="<?php echo $block->escapeHtml(__('Export to CSV') )?>" />
                    </div>
                </div>
            </form>
        </div>
    <script type="text/javascript">
        //< ![CDATA[
        //]]>
        require(['jquery', "mage/template", "jquery/ui"], function($) {
            $(document).ready(function ($) {
                $('.datepicker').datepicker();
            });
        });        
    </script> 
    <script type="text/x-magento-init">
    {
        "#report_filter": {
            "validation": {}
        }
    }
</script>
    <div class="table-responsive">
        <table class="table table-striped">
            <thead>
            <tr>
                <th><?php echo $block->escapeHtml(__('Period')); ?></th>
                <th><?php echo $block->escapeHtml(__('Products Name')); ?></th>
                <th><?php echo $block->escapeHtml(__('Price')); ?></th>
                <th><?php echo $block->escapeHtml($block->getLastColumnHeader()); ?></th>
            </tr>
            </thead>
            <tbody>
                <?php $sumItemCount = 0; ?>
                <?php $sumQtySold = 0; ?>
                <?php $sumSubtotal = 0; ?>
                <?php $sumIncome = 0; ?>
                <?php $viewSubtotal = 0; ?>
                <?php if($_items->count() > 0): ?>
                    <?php foreach($_items AS $_item) : ?>
                        <?php $sumItemCount += $_item->getItemCount(); ?>
                        <?php $sumQtySold += $_item->getQtyOrdered(); ?>
                        <?php $sumSubtotal += $_item->getProductPrice(); ?>
                        <?php $viewSubtotal += $_item->getViewsNum(); ?>
                        <tr>
                            <td><?php echo $block->getPeriodString($_item->getPeriod()); ?></td>
                            <td><?php echo $block->escapeHtml($_item->getProductName()); ?></td>
                            <td><?php echo $block->getCurrencyHelper()->currency($_item->getProductPrice()); ?></td>
                            <td><?php echo number_format($_item->getViewsNum()); ?></td>
                        </tr>
                    <?php endforeach; ?>
            <?php else : ?>
                    <tr>
                        <td colspan="4"><?php echo $block->escapeHtml(__('No records found.')); ?></td>
                    </tr>
            <?php endif; ?>
            </tbody>
            <tfoot>
            <tr>
                <td class="info" colspan="2"><?php echo $block->escapeHtml(__('Total')); ?></td>
                <td class="info"><?php echo $block->getCurrencyHelper()->currency($sumSubtotal); ?></td>
                <td class="info"><?php echo $block->escapeHtml($viewSubtotal); ?></td>
            </tr>
            </tfoot>
        </table>
    </div>
</div>