<?php $categories = $block->getCategories(); ?>
<?php $product = $block->getProduct(); ?>
<?php $attributes = $block->getAttributes($product); ?>
<?php $selectedCategories = $product->getCategoryIds(); ?>
<?php $mediaGallery = $product->getMediaGalleryImages(); ?>
<?php $productMediaVideoHelper = $block->getProductMediaVideoHelper(); ?>
<?php $videoUrl = $productMediaVideoHelper->getVideoUrl($product); ?>
<?php $block->setSelectedCategories($selectedCategories); ?>
<?php $productData = $product->getData();?>

<div class="container main-container vendor-container">
    <h1 class="text-center">
        <?php /* @escapeNotVerified */ echo __('Edit Product'); ?> - <?php echo $product->getName(); ?>
        <small>(<?php /* @escapeNotVerified */ echo __('SKU'); ?>: <?php echo $product->getSku(); ?>)</small>
    </h1>
    <?php if ($product->getAdminProductNote() !== null) : ?>
        <div class="alerts">
            <div class="alert-message info">
                <a class="close" href="#">×</a>

                <p>
                    <strong><?php /* @escapeNotVerified */ echo __('Admin Remark'); ?>:</strong>
                    <?php echo $product->getAdminProductNote(); ?></p>
            </div>
        </div>
    <?php endif; ?>

    <div class="row">
        <div class="col-md-12 form-container">
            <form name="product_create_form" id="product_create_form"
                  action="<?php echo $block->getUrl('supplier/product/save') ?>" method="post"
                  enctype="multipart/form-data">
                <input type="hidden" name="attribute_set_id" value="<?php echo $product->getAttributeSetId(); ?>"/>
                <input type="hidden" name="product_id" value="<?php echo $product->getId(); ?>"/>
                <input type="hidden" name="type" value="<?php echo $block->getProductTypeId(); ?>"/>

                <div class="col-md-6 col-sm-6">
                    <div class="container form-group">
                        <div class="col-md-3 label-container">
                            <label for="name">
                                <?php echo $block->getLabel('name', 'Name', false); ?>
                                <span class="required">*</span>:
                            </label>
                        </div>
                        <div class="col-md-5 input-container">
                            <input type="text"
                                   id="name"
                                   name="name"
                                   class="input-text form-control required-entry"
                                   value="<?php echo $product->getData('name'); ?>"
                            />
                        </div>
                    </div>
                    <div class="container form-group">
                        <div class="col-md-3 label-container">
                            <label for="short_description">
                                <?php echo $block->getLabel('short_description', 'Short Description', false); ?>
                                <span class="required">*</span>:
                            </label>
                        </div>
                        <div class="col-md-5 input-container">
                            <textarea id="short_description"
                                      name="short_description"
                                      class="input-text form-control required-entry form-control wysiwyg validate-length minimum-length-1"
                                      rows="15"><?php echo $product->getData('short_description'); ?></textarea>
                            <div id="short_description_error_required_field_label" class="cminds_error" style="dфplay:none">
                                <?php echo $block->escapeHtml(__('This is a required field')); ?>
                            </div>
                        </div>
                    </div>
                    <div class="container form-group">
                        <div class="col-md-3 label-container">
                            <label for="description">
                                <?php echo $block->getLabel('description', 'Detailed Description ', false); ?>
                                <span class="required">*</span>:
                            </label>
                        </div>
                        <div class="col-md-5 input-container">
                            <textarea id="description"
                                      name="description"
                                      class="input-text form-control form-control required-entry wysiwyg"
                                      rows="15"><?php echo $product->getData('description'); ?></textarea>
                            <div id="description_error_required_field_label" class="cminds_error" style="display:none">
                                <?php echo $block->escapeHtml(__('This is a required field')); ?>
                            </div>
                        </div>
                    </div>
                    <div class="container form-group">
                        <div class="col-md-3 label-container">
                            <label for="price">
                                <?php echo $block->getLabel('price', 'Price', false); ?>
                                <span class="required">*</span>
                                <?php echo " " . $block->getCurrentCurrencySymbol(); ?>:
                            </label>
                        </div>
                        <div class="col-md-5 input-container">
                            <input type="text"
                                   id="price"
                                   name="price"
                                   value="<?php /* @escapeNotVerified */ echo isset($productData['price']) ? $block->getStorePrice($productData['price']) : ''; ?>"
                                   class="input-text form-control required-entry validate-number"
                            />
                        </div>
                    </div>
                    <div class="container form-group">
                        <div class="col-md-3 label-container">
                            <label for="special_price">
                                <?php echo $block->getLabel('special_price', 'Special Price', false); ?>
                                <?php echo " " . $block->getCurrentCurrencySymbol(); ?>:
                            </label>
                        </div>
                        <div class="col-md-5 input-container">
                            <input type="text"
                                   id="special_price"
                                   name="special_price"
                                   value="<?php /* @escapeNotVerified */ echo isset($productData['special_price']) ? $block->getStorePrice($productData['special_price']) : ''; ?>"
                                   class="input-text form-control validate-number"
                            />
                        </div>
                    </div>
                    <div class="container form-group">
                        <div class="col-md-3 label-container">
                            <label for="special_price_from_date">
                                <?php echo $block->getLabel('special_price_from_date', 'Special Price From', false); ?>:
                            </label>
                        </div>
                        <div class="col-md-5 input-container">
                            <input type="text"
                                   id="special_price_from_date"
                                   name="special_price_from_date"
                                   value="<?php echo isset($productData['special_from_date']) ? date('m/d/Y', strtotime($productData['special_from_date'])) : ''; ?>"
                                   class="input-text form-control datepicker"
                            />
                        </div>
                    </div>
                    <div class="container form-group">
                        <div class="col-md-3 label-container">
                            <label for="special_price_to_date">
                                <?php echo $block->getLabel('special_price_to_date', 'Special Price To', false); ?>:
                            </label>
                        </div>
                        <div class="col-md-5 input-container">
                            <input type="text"
                                   id="special_price_to_date"
                                   name="special_price_to_date"
                                   value="<?php echo isset($productData['special_to_date']) ? date('m/d/Y', strtotime($productData['special_to_date'])) : ''; ?>"
                                   class="input-text form-control datepicker"
                            />
                        </div>
                    </div>
                    <div class="container form-group">
                    <?php
                        // if only one source specified
                        if($block->inventoryIsSingleSourceMode()): ?>
                            <div class="col-md-3 label-container">
                                <label for="qty">
                                    <?php echo $block->getLabel('qty', 'QTY Available', false); ?>
                                    <span class="required">*</span>:
                                </label>
                            </div>
                            <div class="col-md-5 input-container">
                                <input type="text"
                                       id="qty"
                                       name="qty"
                                       value="<?php echo $block->getQty($product->getId()) ?>"
                                       class="input-text form-control validate-number required-entry"
                                />
                            </div>
                        <?php else: ?>
                            <div class = 'source-container col-md-5 input-container'>
                                <div class="label-container">
                                    <label for="qty">
                                        <?php /* @escapeNotVerified */ echo $block->getLabel('qty', __('Assigned Sources'), false); ?>
                                        <!-- <span class="required">*</span> -->:
                                    </label>
                                </div>
                                <div class="input-container">
                                    <div class="col-md-6 ">
                                        <select class="source-selector">
                                        <?php
                                        $cnt=1;
                                        foreach ($block->getInventorySourcesArray() as $option):
                                        ?>
                                        <option value="<?= $option['code'] ?>"
                                            data-code="<?= $option['code'] ?>"
                                            data-id="<?= $cnt++ ?>"
                                            data-enabled="<?= $option['enabled'] ?>"><?= $option['name'] ?></option>
                                        <?php
                                        endforeach;
                                        ?>
                                        </select>
                                    </div>
                                    <div class="col-md-6 ">
                                        <button type='button' class = 'add-source'><?php /* @escapeNotVerified */ echo $block->getLabel('qty', __('Assign Source'), false); ?></button>
                                    </div>
                                </div>
                                <div class="label-container source-list">
                                    <?php
                                    $sources = $block->getInventorySourcesBySku($product->getSku());
                                    if( count($sources) ){
                                        foreach ($sources as $item) {
                                    ?>
                                        <div class="option-row">
                                            <div class="name col-md-4"><?= $item['name'] ?></div>
                                            <div class="status col-md-2"><?= $item['enabled'] ? __('enabled') : __('disabled') ?></div>
                                            <div class="value col-md-2">
                                                <input id="option-<?= $item['code'] ?>" name="sources[<?= $item['code'] ?>][inv]" value="<?= $item['qty'] ?>">
                                            </div>
                                            <div class="value col-md-3">
                                                <select id="option-<?= $item['code'] ?>-status" name="sources[<?= $item['code'] ?>][status]">
                                                    <option value="1" <?= $item['status'] ? 'selected="selected"' : '' ?>><?php /* @escapeNotVerified */ echo $block->getLabel('qty', __('In Stock'), false); ?></option>
                                                    <option value="0" <?= $item['status'] ? '' : 'selected="selected"' ?>><?php /* @escapeNotVerified */ echo $block->getLabel('qty', __('Out Of Stock'), false); ?></option>
                                                </select>
                                            </div>
                                            <div class="action col-md-1"><a href='#' class='remove-row' title="<?php /* @escapeNotVerified */ echo $block->getLabel('qty', __('Unassign'), false); ?>"><b>X</b></a></div>
                                        </div>
                                    <?php
                                        }
                                    }
                                    ?>
                                </div>
                            </div>
<script type="text/javascript">
    //< ![CDATA[
    require([
      'jquery'
    ], function ($) {
        $(document).ready(function ()  {
            $(document).on('click', '.source-container .add-source', function (e) {
                var $container = $(this).closest('.source-container');
                var $option = $container.find('.source-selector').children("option:selected");
                var optionId = 'source-option-' + $option.data('id');
                // if option not added
                if( !$container.find('#' + optionId ).length ) {
                    var html = $('<div>', {
                      'class' : 'option-row'
                    });
                    $(html).append(
                        $("<div></div>",{
                            'class': 'name col-md-4',
                            text: $option.html()
                        })
                    ).append(
                        $("<div></div>",{
                            'class': 'status col-md-2',
                            text: $option.data('enabled') ? 'enabled' : 'disabled'
                        })
                    ).append(
                        $("<div></div>",{
                            'class': 'value col-md-2',
                        }).append(
                            $('<input>', {
                                'id': optionId,
                                'name' : 'sources['+$option.data('code')+'][inv]',
                                'value' : 0
                            })
                        )
                    ).append(
                        $("<div></div>",{
                            'class': 'value col-md-3',
                        }).append(
                            $('<select>', {
                                'id': optionId + '-status',
                                'name' : 'sources['+$option.data('code')+'][status]',
                            }).append('<option value="1" selected="selected"><?php /* @escapeNotVerified */ echo $block->getLabel('qty', __('In Stock'), false); ?></option>')
                            .append('<option value="0"><?php /* @escapeNotVerified */ echo $block->getLabel('qty', __('Out Of Stock'), false); ?></option>')
                        )
                    ).append(
                        $("<div></div>",{
                            'class': 'action col-md-1'
                        }).append(
                            $('<a>', {
                                html: "<b>X</b>",
                                'title': "<?php /* @escapeNotVerified */ echo $block->getLabel('qty', __('Unassign'), false); ?>",
                                'class': 'remove-row',
                                'href': '#'
                            })
                        )
                    );

                    // var html = "<div id = '" +optionId+ "'><div>"+$option.html()+"</div><div>"+( $option.data('enabled') ? 'enabled' : 'disabled' ) +"</div></div>";
                    $container.find('.source-list').append(html);
                }
            });
            $(document).on('click', '.option-row a.remove-row', function(e){
                e.preventDefault();
                $( this ).closest( ".option-row" ).remove();
            });
        });
    });
                            //]]>
                          </script>
                        <?php endif; ?>
                    </div>
                    <?php $typeId = $block->getDataParams();
                    if ($typeId['type'] === 'simple' || $typeId['type'] === 'configurable') : ?>
                        <div class="container form-group">
                            <div class="col-md-3 label-container">
                                <label for="weight">
                                    <?php echo $block->getLabel('weight', 'Product Weight', false); ?>
                                    <span class="required">*</span>:
                                </label>
                            </div>
                            <div class="col-md-5 input-container">
                                <input type="text"
                                       id="weight"
                                       name="weight"
                                       value="<?php echo $product->getData('weight'); ?>"
                                       class="input-text form-control validate-number required-entry"
                                />
                            </div>
                        </div>
                    <?php endif; ?>
                    <?php foreach ($attributes as $attribute) : ?>
                        <?php $attributeObj = $block->getAttribute($attribute['attribute_code']); ?>
                        <?php if ((int)$attributeObj->getData('available_for_supplier') === 0) : ?>
                            <?php continue; ?>
                        <?php endif; ?>
                        <?php if ((count($attributeObj->getApplyTo()) === 0 || in_array('simple', $attributeObj->getApplyTo()))) : ?>
                            <?php $attributeFrontend = $attributeObj->getFrontend(); ?>
                            <?php $isRequired = (int)$attributeFrontend->getAttribute()->getIsRequired(); ?>
                            <div class="container form-group">
                                <div class="col-md-3 label-container">
                                    <label for="product_name">
                                        <?php echo $block->getLabel($attributeObj); ?>
                                        <?php if ($isRequired === 1) : ?>
                                            <span class="required">*</span>
                                        <?php endif; ?>
                                    </label>
                                </div>
                                <div class="col-md-5 input-container">
                                    <?php echo $block->getAttributeHtml($attributeObj, $productData); ?>
                                </div>
                            </div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                    <?php if ($product->getAdminProductNote() !== null) : ?>
                        <div class="container form-group">
                            <div class="col-md-3 label-container">
                                <label for="notify_admin_about_change">
                                    <?php /* @escapeNotVerified */ echo __('Notify Admin About Change'); ?>
                                </label>
                            </div>
                            <div class="col-md-3 input-container">
                                <input type="checkbox"
                                       name="notify_admin_about_change"
                                       id="notify_admin_about_change"
                                       value="1"
                                />
                            </div>
                        </div>
                    <?php endif; ?>
                </div>

                <div class="col-md-4 col-sm-5 col-sm-offset-1 col-md-offset-1 right sidebar">
                    <div class="form-group">
                        <?php if ($block->canAddImages()) : ?>
                            <div class="col-md-12 photo-content">
                                <h5><?php /* @escapeNotVerified */ echo __('Product Images'); ?></h5>

                                <div class="col-md-12">
                                    <div class="row">
                                        <span class="file_upload_span btn btn-primary">
                                            <?php /* @escapeNotVerified */ echo __('Select and Upload Image') ?>
                                        </span>
                                        <input type="file" name="file_upload" id="file_upload" multiupload/>
                                    </div>
                                </div>
                                <?php $mainPhotoImage = ''; ?>
                                <?php foreach ($mediaGallery as $img) : ?>
                                    <?php if ($product->getImage() === $img->getFile()) : ?>
                                        <?php $mainPhotoImage = $product->getImage() ?>
                                    <?php endif; ?>
                                <?php endforeach; ?>

                                <input type="hidden"
                                       class="image hidden"
                                       name="main_photo"
                                       id="main_photo"
                                       value="<?php echo $mainPhotoImage ?>"
                                />

                                <div class="col-md-8 photos">
                                    <ul class="photo panel-body">
                                    <?php foreach ($mediaGallery as $img) : ?>
                                        <?php if (file_exists($block->getMediaPath().'/catalog/product' . $img->getFile())) : ?>
                                            <li class="thumbnail<?php echo ($mainPhotoImage == $img->getFile()) ? ' main' : '' ?>">
                                                <img src="<?php echo $block->getMediaUrl().'catalog/product' . $img->getFile(); ?>"
                                                     data-name="<?php echo $img->getFile(); ?>"
                                                />
                                                <span class="remove">
                                                    <i class="glyphicon glyphicon-remove"></i>
                                                </span>
                                                <span class="default">
                                                    <i class="glyphicon glyphicon-home"></i>
                                                </span>
                                                <input type="hidden"
                                                       class="image hidden"
                                                       name="image[]"
                                                       value="<?php echo $img->getFile(); ?>"
                                                />
                                            </li>
                                        <?php endif; ?>
                                    <?php endforeach; ?>
                                    </ul>
                                </div>
                            </div>
                        <?php endif;?>
                        <?php if ($productMediaVideoHelper->canAddVideos()) : ?>
                            <div class="col-md-12 photo-content">
                                <h5><?php echo __('Product Video'); ?></h5>
                                <?php if (!empty($videoUrl)) : ?>
                                    <a href="<?php echo $videoUrl; ?>"
                                       target="_blank"><?php /* @escapeNotVerified */ echo __('Current video'); ?></a>
                                <?php endif; ?>
                                <input type="text"
                                       name="video_url"
                                       value=""
                                       id="video_url"
                                />
                            </div>
                        <?php endif;?>
                    </div>

                    <ul class="category-list">
                        <div style="display:none;color:red;" id="categories-validate-message"></div>
                        <h5><?php /* @escapeNotVerified */ echo __('Product Categories'); ?></h5>
                        <?php echo $block->getNodes($categories); ?>
                    </ul>

                    <script>
                        require([
                            "jquery"
                        ], function($){
                            $(document).ready(function () {
                                var previousParentsByLevel = [];
                                $(".category-list li").each(function (index, element) {
                                    if ($(element).hasClass('level-2')) {
                                        previousParentsByLevel[2] = $(element);
                                        return;
                                    }
				    if ($(element).hasClass('level-1')) {
                                        previousParentsByLevel[1] = $(element);
                                        return;
                                    }

                                    var elementLevel = $(element).data('level');
                                    previousParentsByLevel[elementLevel] = $(element);
                                    var parent = previousParentsByLevel[elementLevel - 1];
                                    var parentChecked = parent.find('input').prop('checked');


                                    if (!$(element).find('input').prop('checked') && !parentChecked) {
                                        $(element).hide();
                                    }
                                });

                                $(".category-list input").on('change', function(event) {
                                    var input = $(event.target);
                                    var value = $(event.target).prop('checked');

                                    if (value) {
                                        var inputLi = input.parent('li')
                                        var inputLevel = inputLi.data('level');
                                        var parentIndex = $(".category-list li").index(inputLi);
                                        var nextParentFound = false;

                                        $(".category-list li").each(function(index, element) {
                                            if (index <= parentIndex) {
                                                return;
                                            }

                                            if (nextParentFound) {
                                                return;
                                            }

                                            var elementLevel = $(element).data('level');

                                            if (elementLevel <= inputLevel) {
                                                nextParentFound = true;
                                                return;
                                            }

                                            if (elementLevel == inputLevel + 1) {
                                                $(element).show();
                                            }

                                        })
                                    } else {
                                        var inputLi = input.parent('li')
                                        var inputLevel = inputLi.data('level');
                                        var parentIndex = $(".category-list li").index(inputLi);
                                        var nextParentFound = false;

                                        $(".category-list li").each(function(index, element) {
                                            if (index <= parentIndex) {
                                                return;
                                            }

                                            if (nextParentFound) {
                                                return;
                                            }

                                            var elementLevel = $(element).data('level');

                                            if (elementLevel <= inputLevel) {
                                                nextParentFound = true;
                                                return;
                                            }

                                            if (elementLevel >= inputLevel + 1) {
                                                $(element).hide();
                                                $(element).find('input').prop('checked', false);
                                            }

                                        })

                                    }

                                });
                            });





                        });
                    </script>


                    <?php if ($product->getTypeId() === 'downloadable') : ?>
                        <ul class="list-unstyled">
                            <?php foreach ($block->getLinks() as $link) : ?>
                                <?php if ($link->getLinkType() === 'url') : ?>
                                    <h5><?php /* @escapeNotVerified */ echo $link->getTitle(); ?></h5>
                                <?php else : ?>
                                    <h5><?php /* @escapeNotVerified */ echo $link->getTitle(); ?></h5>
                                    <h5><a href="<?php echo $block->getLinkDownloadUrl($link); ?>"><?php /* @escapeNotVerified */ echo $block->getFormatedFileName($link->getLinkFile()); ?></a></h5>
                                    <li>
                                <?php endif; ?>
                                <li>
                                    <?php if ($link->getLinkType() === 'url') : ?>
                                        <input type="text"
                                           id="downloadable_links[<?php echo $link->getId(); ?>]"
                                           name="downloadable_links[<?php echo $link->getId(); ?>][url]"
                                           class="input-text form-control"
                                           value="<?php echo $link->getLinkUrl() ?>"
                                        />
                                        <input type="hidden"
                                               name="downloadable_links_file_<?php echo $link->getId(); ?>"
                                               class="input-text form-control"
                                               value
                                        />
                                    <?php else : ?>
                                        <input type="file"
                                               name="downloadable_links_file_<?php echo $link->getId(); ?>"
                                               id="downloadable_links_file_<?php echo $link->getId(); ?>"
                                        />
                                        <input type="hidden"
                                               name="downloadable_links[<?php echo $link->getId(); ?>][url]"
                                               value
                                        />
                                    <?php endif; ?>

                                    <input type="hidden"
                                           name="downloadable_links[<?php echo $link->getId(); ?>][title]"
                                           class="input-text form-control"
                                           value="<?php echo $link->getTitle(); ?>"
                                    />
                                    <input type="hidden"
                                           name="downloadable_links[<?php echo $link->getId(); ?>][id]"
                                           class="input-text form-control"
                                           value="<?php echo $link->getId() ?>"
                                    />
                                    <input type="hidden"
                                           name="downloadable_links[<?php echo $link->getId(); ?>][file_id]"
                                           class="input-text form-control"
                                           value="downloadable_links_file_<?php echo $link->getId(); ?>"
                                    />
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>
                </div>

                <span class="clearfix"></span>

                <div class="col-md-2 col-sm-4 col-sm-offset-4 col-md-offset-5 btn-save-fix">
                    <input type="submit"
                           name="submit"
                           class="btn btn-primary"
                           value="<?php /* @escapeNotVerified */ echo __('Save Product') ?>"
                    />
                </div>
            </form>
        </div>
    </div>
</div>

<div class="slideshow-container">
    <div class="slideshow"></div>
</div>

<script type="text/javascript">
    //< ![CDATA[
    require([
      'jquery',
      'jquery/fileUploader/jquery.fileupload'
    ], function ($, fileupload) {
        var limitReachedAlertFlag = 0;

        function checkLimit()
        {
            var limit = <?php echo $this->getMaxImagesCount() ?>;

            if (limitReachedAlertFlag) {
                return false;
            }

            if ($('.thumbnail:visible').length >= limit) {
                window.alert('The upload limit has been reached.');
                limitReachedAlertFlag = 1;

                return false;
            }
        }

        $(document).ready(function ()  {
            $('.datepicker').datepicker();

            $(document).on('click', 'li span.remove', function () {
                var img = $j(this).prev();
                var imgName = $j(img).attr('data-name');

                $('input.image.hidden').each(function () {
                    if ($(this).val() === imgName) {
                        $(this).val('');
                    }
                });
                $(this).parent().fadeOut();
            });

            $(document).on('click', 'li span.default', function () {
                var img = $(this).prev().prev();
                var imgName = $(img).attr('data-name');
                var mainPhotoInput = $('#main_photo');
                mainPhotoInput.val(imgName);

                if ($('li.thumbnail.main').length) {
                    $('li.thumbnail.main').removeClass('main');
                }

                img.parent().addClass('main');
            });

            $('#file_upload')
                .fileupload({
                    autoUpload : true,
                    url: '<?php echo $block->getUrl('supplier/product/upload') ?>',
                    done: function (e, data) {
                        var response = data.result;
                        if (response.success) {
                            $('.photo.panel-body').append(
                                '<li class="thumbnail"><img src="' + response.url + '" alt="" data-name="' + response.name + '"/>'
                                + '<span class="remove"><i class="glyphicon glyphicon-remove" title="Remove This Picture"></i></span>'
                                + '<span class="default"><i class="glyphicon glyphicon-home" title="Set As Main Picture"></i></span>'
                                + '<input type="hidden" class="image hidden" name="image[]" value="' + response.name + '" />'
                                + '</li>'
                            );

                            setTimeout(checkLimit, 100);
                        } else {
                            window.alert(response.message);
                        }
                    }
                })
                .parent().addClass($.support.fileInput ? undefined : 'disabled');

            $('#file_upload').click(function () {
                limitReachedAlertFlag = 0;
            });
        });
    });
    //]]>
</script>
<?php $magentoVersion = $this->helper('Cminds\Supplierfrontendproductuploader\Helper\Data')->getMagentoVersion(); ?>
<?php if ($magentoVersion < '2.3.0') { ?>
<script type="text/javascript">
    //< ![CDATA[
    require([
      'jquery',
      'tinymce'
    ], function ($, tinymce) {
        $(document).ready(function ()  {
            function hideEdError(ed)
            {
                var id = ed.id;
                var selector = '#' + id + '_error_required_field_label';
                if (typeof $(selector) !== 'undefined') {
                    $(selector).hide();
                }
            }

            function hideTinymceErrors()
            {
                for (var i = 0; i < tinymce.editors.length; i++) {
                    var ed = tinymce.editors[i];
                    hideEdError(ed);
                }
            }

            function displayTinymceErrorLabel(ed)
            {
                var id = ed.id;
                var selector = '#' + id + '_error_required_field_label';
                if (typeof $(selector) !== 'undefined') {
                    $(selector).show();
                }
            }

            function checkEmpty(ed)
            {
                var content = ed.getContent().replace(/<[^>]*>/ig, ' ')
                    .replace(/<\/[^>]*>/ig, ' ')
                    .replace(/&nbsp;|&#160;/gi, ' ')
                    .replace(/\s+/ig, ' ')
                    .trim();

                if (content === '') {
                    displayTinymceErrorLabel(ed);

                    return true;
                }

                return false;
            }

            $('#product_create_form').submit(function (e) {
                hideTinymceErrors();

                var emptyTinymceDetected = 0;

                for (var i = 0; i < tinymce.editors.length; i++) {
                    if (checkEmpty(tinymce.editors[i])) {
                        emptyTinymceDetected = 1;
                    }
                }

                if (emptyTinymceDetected) {
                    e.preventDefault();
                }

                return;
            });

            tinymce.init({
                mode : 'textareas',
                theme : 'advanced',
                theme_advanced_toolbar_location: 'top',
                theme_advanced_buttons1 : 'bold,italic,underline,|,fontselect,fontsizeselect,|,forecolor,backcolor,|,bullist,numlist',
                theme_advanced_buttons2 : '',
                theme_advanced_buttons3 : '',
                theme_advanced_toolbar_align : 'left'
            });

        });
    });
    //]]>
</script>
<?php } else { ?>
<script>
    require([
    "jquery",
    "mage/translate",
    "mage/adminhtml/events",
    "mage/adminhtml/wysiwyg/tiny_mce/setup"
    ], function($){
        $(document).ready(function ()  {
            wysiwygshort_description = new wysiwygSetup("short_description", {
              "width":"99%",  // defined width of editor
              "height":"200px", // height of editor
              "plugins":[{"name":"image"}], // for image
              "tinymce4":{"toolbar":"formatselect | bold italic underline | alignleft aligncenter alignright | bullist numlist | link table charmap","plugins":"advlist autolink lists link charmap media noneditable table contextmenu paste code help table",
              }
            });
            wysiwygshort_description.setup("exact");

            wysiwygdescription = new wysiwygSetup("description", {
              "width":"99%",  // defined width of editor
              "height":"200px", // height of editor
              "plugins":[{"name":"image"}], // for image
              "tinymce4":{"toolbar":"formatselect | bold italic underline | alignleft aligncenter alignright | bullist numlist | link table charmap","plugins":"advlist autolink lists link charmap media noneditable table contextmenu paste code help table",
              }
            });
            wysiwygdescription.setup("exact");
        });
    });
</script>
<?php } ?>
<script type="text/x-magento-init">
    {
        "#product_create_form": {
            "validation": {}
        }
    }
</script>
