<?php
/** @var $block \Cminds\Marketplace\Block\Supplier */

$vendor = $block->getRegistry('current_customer');
$customFields = $block->getCustomFieldsValues(true);
$newCustomFields = $block->getNewCustomFieldsValues(true);
?>

<div class="entry-edit">
    <div id="messages">
        <ul class="messages">
            <?php if ($vendor->getSupplierProfileApproved()) : ?>
                <li class="success-msg">
                    <ul>
                        <li>
                            <span>
                                <?= /* @escapeNotVerified */ $block->escapeHtml(__('This profile is activated')); ?>
                            </span>
                            <button type="button"
                                    id="button_disapprove"
                                    class="scalable delete"
                                    style="float:right;">
                                <span>
                                    <?= /* @escapeNotVerified */ $block->escapeHtml(__('Disapprove')); ?>
                                </span>
                            </button>
                        </li>
                    </ul>
                </li>
            <?php else : ?>
                <li class="warning-msg">
                    <ul>
                        <li>
                            <span>
                                <?= /* @escapeNotVerified */ $block->escapeHtml(__('This profile is not approved')); ?>
                            </span>
                            <button type="button"
                                    id="button_activate"
                                    class="scalable save"
                                    style="float:right;">
                                    <span>
                                        <?= /* @escapeNotVerified */ $block->escapeHtml(__('Approve')); ?>
                                    </span>
                            </button>

                            <button type="button"
                                    id="button_add_remark"
                                    class="scalable"
                                    style="float:right; margin-right: 5px;">
                                    <span>
                                        <?= /* @escapeNotVerified */  $block->escapeHtml(__('Add Remark')); ?>
                                    </span>
                            </button>
                        </li>
                    </ul>
                </li>
                <div id="remark" style="display: none;">
                    <p>
                        <h4>
                            <?= /* @escapeNotVerified */ $block->escapeHtml(__('Add Remark to This Vendor Profile')); ?>
                        </h4>
                    </p>

                    <p>
                        <textarea
                            name="remark"
                            data-form-part="customer_form"
                            id="remark"
                            cols="30"
                            rows="10"></textarea>
                    </p>

                    <p>
                        <button type="button"
                                id="button_add_remark_save"
                                class="scalable save"
                                style="">
                                <span>
                                    <?= /* @escapeNotVerified */ $block->escapeHtml(__('Save Remark')); ?>
                                </span>
                        </button>
                    </p>
                    <hr>
                </div>
            <?php endif; ?>
        </ul>
    </div>

    <input type="hidden"
           name="action"
           data-form-part="customer_form"
           id="form_action"
           value=""/>

    <?php if ($vendor->getSupplierName()) : ?>
        <p>
            <strong>
                <?= $block->escapeHtml($vendor->getSupplierName()); ?>
            </strong>
            <small>
                [<a
                    href="javascript:void();"
                    title="<?= /* @escapeNotVerified */ $block->escapeHtml(__('Current Supplier Name')); ?>"
                >?</a>]
            </small>
        </p>
    <?php endif; ?>

    <p>
        <a href="<?= $block->getHelper()->getSupplierRawPageUrl($vendor->getId(),'adminhtml'); ?>" target="_blank">
            <?= /* @escapeNotVerified */  __('Supplier page'); ?>
        </a>
    </p>

    <?php if ($vendor->getSupplierLogo()) : ?>
        <p>
            <img style="width: 100px"
                 src="<?= $block->getHelper()->getSupplierLogo($vendor->getId()); ?>"
                 alt="<?= $block->escapeHtml($vendor->getSupplierName()); ?>"/>
        </p>
    <?php else : ?>
        <p style="clear:both;">
            <img src="http://placehold.it/100x100" />
        </p>
    <?php endif; ?>

    <?php if ($vendor->getSupplierDescription()) : ?>
        <p>
            <?= $block->escapeHtml($vendor->getSupplierDescription()); ?>
            <small>
                [<a
                    href="javascript:void();"
                    title="<?= /* @escapeNotVerified */ $block->escapeHtml(__('Current Supplier Description')); ?>">?</a>
                ]</small>
        </p>
    <?php endif; ?>

    <?php if ($customFields): ?>
        <?php foreach ($customFields as $customField): ?>
            <?php if ($customField['value'] !== ''): ?>
                <br>
                <div>
                    <strong><?= $block->getFieldLabel($customField['name']); ?></strong>
                </div>
                <div>
                    <?= $customField['value']; ?>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
    <?php endif; ?>
</div>

<div class="entry-edit">
    <h3 style="margin-top: 40px;"><?= /* @escapeNotVerified */ $block->escapeHtml(__('Data Waiting For Approval')); ?>
        <button type="button"
                class="scalable save"
                id="button_approve_changes"
                style="float:right;">
                <span>
                    <?= /* @escapeNotVerified */ $block->escapeHtml(__('Approve Changes')); ?>
                </span>
        </button>
    </h3>

    <?php echo $block->getFormHtml();?>
</div>

<script type="text/javascript">
    //<![CDATA[
    jQuery(document).ready(function($){
        function saveAndContinueEdit(urlTemplate) {
            $('#save_and_continue').trigger('click');
        }

        if($('#button_add_remark')) {
            $('#button_add_remark').click(function (e) {
                e.preventDefault();
                $('#remark').show();
            });
        }

        if($('#button_activate')) {
            $('#button_activate').click(function (e) {
                e.preventDefault();
                $('#form_action').val('approve');
                saveAndContinueEdit('<?php echo $block->escapeHtml($this->getSaveAndContinueUrl()); ?>');
            });
        }

        $('#button_approve_changes').click(function(e){
            if(!$('#supplier_profile_name_new').val()
                && !$('#supplier_profile_name_new').val()
            ) {
                if(!confirm('New data is empty, do you want to continue ?')) {
                    return;
                }
            }
            e.preventDefault();

            $('#form_action').val('approve_changes');
            saveAndContinueEdit('<?php echo $block->escapeHtml($this->getSaveAndContinueUrl()); ?>');
        });

        if($('#button_add_remark_save')) {
            $('#button_add_remark_save').click(function (e) {
                e.preventDefault();
                $('#form_action').val('save_remark');
                saveAndContinueEdit('<?php echo $block->escapeHtml($this->getSaveAndContinueUrl()); ?>');
            });
        }

        if($('#button_disapprove')) {
            $('#button_disapprove').click(function (e) {
                e.preventDefault();
                $('#form_action').val('disapprove');
                saveAndContinueEdit('<?php echo $block->escapeHtml($this->getSaveAndContinueUrl()); ?>');
            });
        }
    });
    //]]>
</script>
