<?php $customer = $block->getCustomer(); ?>
<div class="container main-container vendor-container">
    <h1><?php echo __('Notifications'); ?></h1>
    <div class="row">
        <div class="col-md-12 container form-container">
            <form name="settings_shipping_methods"
                  id="settings_shipping_methods"
                  action="<?php echo $block->getUrl('*/*/savenotificationsettings') ?>"
                  method="post">
                <?php if ($block->canConfigureOrderedProductsNotification()) : ?>
                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="radio">
                                <div class="checkbox">
                                    <?php
                                    $checked = (int)$customer->getData('notification_product_ordered') === 1
                                        ? 'checked'
                                        : '';
                                    ?>
                                    <input type="checkbox"
                                           id="send_notification_after_product_purchased"
                                           name="send_notification_after_product_purchased"
                                           value="1"
                                        <?php echo $checked ?>
                                    >
                                    <label for="send_notification_after_product_purchased">
                                        <?php echo __('Send notification when my products was ordered'); ?>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <?php endif; ?>

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <div class="radio">
                                <div class="checkbox">
                                    <?php
                                    $checked = (int)$customer->getData('notification_product_approved') === 1
                                        ? 'checked'
                                        : '';
                                    ?>
                                    <input type="checkbox"
                                           id="send_notification_when_product_approved"
                                           name="send_notification_when_product_approved"
                                           value="1"
                                        <?php echo $checked ?>
                                    >
                                    <label for="send_notification_when_product_approved">
                                        <?php echo __('Send notification when my products was approved by admin'); ?>
                                    </label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-2 row">
                    <input type="submit"
                           name="submit"
                           class="btn btn-primary"
                           value="<?php echo __('Save Settings') ?>"/>
                </div>
            </form>
        </div>
    </div>
</div>