<div class="container main-container vendor-container">
    <h1><?php echo __('API'); ?></h1>
    <div class="row">
        <div class="col-md-12 container form-container">
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="logo" class="control-label"><?php echo __('Token'); ?>:</label>
                        <?php echo $block->getApiToken(); ?>
                    </div>
                </div>
            </div>                
        </div>
    </div>
</div>