<?php $order = $block->getOrder(); ?>
<?php $items = $block->getItems(); ?>
<?php $shippingAddress = $block->getOrder()->getShippingAddress(); ?>
<?php $billingAddress = $block->getOrder()->getBillingAddress(); ?>
<?php $canSave = 0; ?>
<div class="container-fluid main-container vendor-container">
    <div class="col-md-10 col-sm-10 col-sm-offset-2 nopadding">
        <h2 class="text-left"><?php echo $block->escapeHtml(__('Create Invoice for Order')); ?>
        #<?php echo $block->escapeHtml($order->getIncrementId()); ?></h2>
    </div>
        <div class="container">
            <div class="row text-left col-md-offset-2">
                <div class="col-md-5">
                    <h3><?php echo /* @escapeNotVerified */ __('Order Information'); ?></h3>
                    <p>
                        <strong><?php echo /* @escapeNotVerified */ __('Order Date'); ?> : </strong>
                        <?php echo date('M d, Y g:i:s A', strtotime($block->escapeHtml($order->getCreatedAt()))); ?>
                    </p>
                    <p>
                        <strong><?php echo $block->escapeHtml(__('Order Status')); ?> : </strong>
                        <?php if ($order->getStatus() == 'canceled') : ?>
                            <span class="text-danger"><?php
                                echo ucfirst($block->escapeHtml($order->getStatus()));
                            ?></span>
                        <?php else : ?>
                            <?php echo ucfirst($block->escapeHtml($order->getStatus())); ?>
                        <?php endif; ?>
                    </p>
                </div>
                <div class="col-md-5">
                    <h3><?php echo /* @escapeNotVerified */ __('Account Information'); ?></h3>
                    <p><strong><?php echo /* @escapeNotVerified */ __('Customer Name'); ?> : </strong>
                        <?php echo $block->escapeHtml($order->getCustomerFirstname()); ?>
                        <?php echo $block->escapeHtml($order->getCustomerLastname()); ?>
                    </p>
                    <p>
                        <strong><?php echo /* @escapeNotVerified */ __('Email'); ?> : </strong>
                        <a href="mailto:<?php echo $block->escapeHtml($order->getCustomerEmail()); ?>">
                            <?php echo $block->escapeHtml($order->getCustomerEmail()); ?>
                        </a>
                    </p>
                </div>
            </div>
        </div>

    <div class="container">
        <div class="row text-left col-md-offset-2">
            <div class="col-md-5">
                <h3><?php echo /* @escapeNotVerified */ __('Billing Address'); ?></h3>
                <p><?php echo ($block->getFormattedBillingAddress()); ?></p>
            </div>
            <div class="col-md-5">
                <h3><?php echo /* @escapeNotVerified */ __('Shipping Address'); ?></h3>
                <p><?php echo ($block->getFormattedShippingAddress()); ?></p>
            </div>
        </div>
    </div>
    <form action="<?php echo $block->getUrl('*/*/save'); ?>" id="createInvoiceForm" method="post">
        <div class="container col-md-7 col-md-offset-2">
            <h2 class="sub-header"><?php echo /* @escapeNotVerified */ __('Items to Invoice'); ?></h2>
            <div class="table-responsive">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th><?php echo /* @escapeNotVerified */ __('Product'); ?></th>
                        <th><?php echo /* @escapeNotVerified */ __('SKU'); ?></th>
                        <th><?php echo /* @escapeNotVerified */ __('Qty Ordered'); ?></th>
                        <th><?php echo /* @escapeNotVerified */ __('Available for Invoice'); ?></th>
                        <th><?php echo /* @escapeNotVerified */ __('Qty'); ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($items as $item) : ?>
                        <?php if ($item->getData('parent_item_id')) : ?>
                            <?php continue; ?>
                        <?php endif; ?>
                        <tr>
                            <td><?php echo $block->escapeHtml($item->getName()); ?></td>
                            <td><?php echo $block->escapeHtml($item->getSku()); ?></td>
                            <td><?php echo $block->escapeHtml(number_format($item->getQtyOrdered())); ?></td>
                            <td><?php echo $item->getQtyOrdered() - $item->getQtyInvoiced(); ?></td>
                            <td>
                                <?php if ($item->getQtyOrdered() - $item->getQtyInvoiced() > 0) : ?>
                                    <?php $canSave = 1; ?>
                                    <input type="text"
                                           class="validate-number form-control required-entry"
                                           name="product[<?php echo $block->escapeHtml($item->getId()); ?>]"
                                           value="<?php echo $item->getQtyOrdered() - $item->getQtyInvoiced(); ?>"
                                    />
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="container ">
            <div class="span12">
                <?php if ($block->getSendEmail()) : ?>
                    <div style="clear: both;"></div>
                    <div class="container form-group col-md-2 col-sm-4 col-sm-offset-2 col-md-offset-2">
                        <div style="text-align: left !important;" class="checkbox">
                            <label for="notify_customer">Notify Customer</label>
                            <input type="checkbox" checked="" value="1" name="notify_customer" id="notify_customer" />
                        </div>
                    </div>
                <?php endif; ?>
                <div style="clear: both;"></div>
                <?php if ($canSave == 1) : ?>
                    <div class="col-md-2 col-sm-4 col-sm-offset-2 col-md-offset-2">
                        <input type="hidden"
                               name="order_id"
                               value="<?php echo $block->escapeHtml($order->getId()); ?>"/>
                        <input type="submit"
                               name="submit"
                               class="btn btn-primary"
                               value="<?php echo /* @escapeNotVerified */ __('Save Invoice')?>"/>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    </form>
</div>