<?php
// @codingStandardsIgnoreFile
?>
<?php $_helper = $this->helper('WeltPixel\CustomHeader\Helper\Data'); ?>
<?php if ($_helper->isGlobalPromoEnabled() ) : ?>
    <div class="global-notification-wrapper" data-mage-init='{"WeltPixel_CustomHeader/js/globalPromo": {}}'>
        <div class="notice-inner">
            <?php echo $this->getChildHtml('global_promo_message_content'); ?>
        </div>
        <a href="javascript: void(0)" class="close-global-notification icon-line-cross"></a>
    </div>
<?php endif; ?>
