<?php $items = $block->getItems(); ?>
<div class="container-fluid main-container vendor-container">
    <h1><?php echo __('Ordered Items') ?></h1>
    <div class="jumbotron">
        <form name="report_filter" id="report_filter" action="<?php echo $block->getUrl('*/*/*') ?>" method="post" enctype="multipart/form-data">
            <div class="row">
                <div class="col-md-3">
                    <input type="text" class="form-control datepicker input-text input-text required-entry validate-date  required-entry" name="from" value="<?php echo $block->escapeHtml($block->getParams()->getParam('from', '')); ?>" placeholder="<?php echo $block->escapeHtml(__('From'))?>*"/>
                </div>
                <div class="col-md-3">
                    <input type="text" class="form-control datepicker input-text required-entry validate-date input-text required-entry" name="to" value="<?php echo $block->escapeHtml($block->getParams()->getParam('to', '')); ?>" placeholder="<?php echo $block->escapeHtml(__('To'))?>*"/>
                </div>
                <div class="col-md-2">
                    <input type="submit" name="submit" class="btn btn-primary btn-sm" value="<?php echo __('Show Report') ?>" />
                </div>
                <div class="col-md-2">
                    <input type="submit" name="submit" class="btn btn-info btn-sm" value="<?php echo __('Export to CSV') ?>" />
                </div>
            </div>
        </form>
    </div>
        <table class="table table-striped">
            <thead>
                <th></th>
                <th><?php echo __('Name') ?></th>
                <th><?php echo __('Product SKU') ?></th>
                <th><?php echo __('Quantity Sold') ?></th>
                <th><?php echo __('Subtotal') ?></th>
            </thead>
            <tbody>
            <?php if($items->count()): ?>
                <?php foreach($items AS $item): ?>
                    <?php $product = $block->getLoadedProduct($item->getProductId()) ?>
                    <tr class="item">
                        <td style="text-align: center;">
                            <a href="<?php echo $product->getProductUrl() ?>" target="blank">
                            <img
                                src="<?php echo $block->getProductImageUrl($product); ?>"
                                alt=""/>
                            </a>
                        </td>
                        <td>
                            <a href="<?php echo $product->getProductUrl() ?>" target="blank"><?php echo $product->getName(); ?>
                            </a>
                        </td>
                        <td><?php echo $product->getSKU(); ?></td>
                        <td><?php echo intval($item->getItemCount()); ?></td>
                        <td><?php echo $block->getCurrencyHelper()->currency($item->getRowTotal()); ?></td>
                    </tr>
                        <?php endforeach; ?>
                    <?php else: ?>
                <td colspan="7"><?php echo $block->escapeHtml(__('No records found.')); ?></td>
                    <?php endif; ?>
            </tbody>
            <tfoot>
                <td></td>
                <td><?php echo __('Name') ?></td>
                <td><?php echo __('Product SKU') ?></td>
                <td><?php echo __('Quantity Sold') ?></td>
                <td><?php echo __('Subtotal') ?></td>
            </tfoot>
        </table>
        <?php
//        echo $this->getLayout()->createBlock('core/template')
//            ->setTemplate('supplierfrontendproductuploader/product/list/pagination.phtml')
//            ->setCollection($_items)
//            ->toHtml() ?>
</div>

<script type="text/javascript">
    require(['jquery', "mage/template", "jquery/ui"], function($) {
        $(document).ready(function ($) {
            $('.datepicker').datepicker();
        });
    });
</script>
<script type="text/x-magento-init">
    {
        "#report_filter": {
            "validation": {}
        }
    }
</script>
